### ISSUE TITLE
Slow performance on custom array types

### ISSUE THREAD

**Issue by apkille** [YingboMa/FastBroadcast.jl#67]
Fast broadcasting on custom array types gives slower performance than pure Julia arrays. This issue is also seen when solving different equations on custom types.

MWE posted in slack by @oscardssmith (using the test example https://github.com/SciML/OrdinaryDiffEq.jl/blob/4a110ca8761845b3aa667a109583775c4c718132/test/interface/noindex_tests.jl):
```
julia> a = NoIndexArray(ones(10, 10));

julia> b = ones(10,10);

julia> using FastBroadcast

julia> @btime @.. a += 1;
  94.690 ns (1 allocation: 32 bytes)

julia> @btime @.. b += 1;
  31.152 ns (1 allocation: 32 bytes)
```

**Comment by chriselrod** [comment]
That is because it defines `NoIndexStyle`.
```julia
julia> @btime @.. $a += 1;
  50.953 ns (0 allocations: 0 bytes)

julia> @btime @.. $b += 1;
  11.011 ns (0 allocations: 0 bytes)

julia> @btime @. $a += 1;
  50.962 ns (0 allocations: 0 bytes)

julia> @btime @. $b += 1;
  20.937 ns (0 allocations: 0 bytes)

julia> copyto!(a, Base.Broadcast.Broadcasted(+, (a, 1)));

julia> @btime copyto!($a, Base.Broadcast.Broadcasted(+, ($a, 1)));
  54.229 ns (0 allocations: 0 bytes)
```
If you don't want a slow broadcast, don't define a custom slow broadcast method.

**Comment by chriselrod** [comment]
To be clear, `FastBroadcast` only applies to `DefaultArrayStyle`.

If it is any other style, e.g. for `StaticArray`s, `GPUArray`s, or sSparseArray`s, the assumption is that this was done for a good reason, i.e. specifically because the creator of that array type wants to opt out of normal broadcast behavior, because they can implement it better for their array type.

**Comment by apkille** [comment]
Thanks, this was very helpful. This may be a naive question, but could you please explain why the `copyto!` method for `NoIndexArray` is slow? This is also how it is done in Julia base for `AbstractArray`: https://github.com/JuliaLang/julia/blob/116d42be2f258048cb84756c14fc6e3adbb6b66d/base/broadcast.jl#L960-L976.

**Comment by chriselrod** [comment]
```julia
julia> @btime @.. $a += 1;
  50.953 ns (0 allocations: 0 bytes)

julia> Base.@propagate_inbounds Base.Broadcast._broadcast_getindex(x::NoIndexArray, i) = x.x[i]

julia> @btime @.. $a += 1;
  21.879 ns (0 allocations: 0 bytes)
```

**Comment by apkille** [comment]
Wow, that is an easy fix 😅. Thanks again!
